GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/655d90ca352224413c0d7bf5

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "web dev simplified"
}

###

DELETE http://localhost:3000/subscribers/655d90ca352224413c0d7bf5

###

PATCH http://localhost:3000/subscribers/655d964bf9ed4b5303f01609
Content-Type: application/json

{
    "name": "New find"
}
